### ISSUE TITLE
Feature request: Update all PRs at once

### ISSUE THREAD

**Issue by ruggi99** [slurps-mad-rips/gh-update-branch#2]
Hi, great and useful extension.
Can we add a `all` subcommand to update all PR's at once?

Thanks

**Comment by bruxisma** [comment]
PRs are welcome!

When I wrote this, I was at a company where the `update branch` button was used a bunch, so having this was convenient. Nowadays, we have a separate main and stable branch at my current employer so I don't currently use this extension anymore, and unfortunately don't have time to dedicate to it.
